// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYU62FYmHEZbaXpKg00XiJVU_SMSnCmM0',
    appId: '1:399261569921:web:f1bcb0335d0d68f0028e80',
    messagingSenderId: '399261569921',
    projectId: 'sensory-sphere-notification',
    authDomain: 'sensory-sphere-notification.firebaseapp.com',
    storageBucket: 'sensory-sphere-notification.appspot.com',
    measurementId: 'G-Q3DYCYHMQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-uKReHWWFXThz5P9-YHMHy8YR2mat4oQ',
    appId: '1:399261569921:android:71800bec34864b50028e80',
    messagingSenderId: '399261569921',
    projectId: 'sensory-sphere-notification',
    storageBucket: 'sensory-sphere-notification.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYU62FYmHEZbaXpKg00XiJVU_SMSnCmM0',
    appId: '1:399261569921:web:3a34b44a6b639712028e80',
    messagingSenderId: '399261569921',
    projectId: 'sensory-sphere-notification',
    authDomain: 'sensory-sphere-notification.firebaseapp.com',
    storageBucket: 'sensory-sphere-notification.appspot.com',
    measurementId: 'G-C6ZG1R9GEH',
  );
}
