// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcAEI2fGVaXs5ScZ18mTv5zpfYVUaH1pU',
    appId: '1:1016611418149:web:9788c914e5c38a8b6d8fcc',
    messagingSenderId: '1016611418149',
    projectId: 'sensory-sphere-8971f',
    authDomain: 'sensory-sphere-8971f.firebaseapp.com',
    storageBucket: 'sensory-sphere-8971f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx74QKmX6FLMu7SzkqBdl1MlJp_fzVlQ8',
    appId: '1:1016611418149:android:5908d6d4196657d36d8fcc',
    messagingSenderId: '1016611418149',
    projectId: 'sensory-sphere-8971f',
    storageBucket: 'sensory-sphere-8971f.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcAEI2fGVaXs5ScZ18mTv5zpfYVUaH1pU',
    appId: '1:1016611418149:web:f2d940f1b62b5d6b6d8fcc',
    messagingSenderId: '1016611418149',
    projectId: 'sensory-sphere-8971f',
    authDomain: 'sensory-sphere-8971f.firebaseapp.com',
    storageBucket: 'sensory-sphere-8971f.appspot.com',
  );

}